### ISSUE TITLE
Updated color palette present in newest GNOME version looks bad, sometimes difficult to read

### ISSUE THREAD

**Issue by dralley** [jnsh/arc-theme#101]
Using arc-theme 20201013 from the Fedora COPR on Fedora 33 with Gnome 3.38.1, the colors are washed out and low-contrast, wheras before they looked fine.

Blue (the shade used for folders when listing directory contents specifically) is the worst.  It is nearly un-readable.

![Screenshot from 2020-11-17 10-13-56](https://user-images.githubusercontent.com/2751996/99409351-45cf2500-28bf-11eb-808e-6142fb8b4102.png)

Compare to Adawaita theme

![Screenshot from 2020-11-17 10-14-21](https://user-images.githubusercontent.com/2751996/99409994-f4736580-28bf-11eb-9197-c12b205a04aa.png)

Green looks kind of bleached and uglier than it used to be but not necessarily difficult to read.

![Screenshot from 2020-11-17 10-16-15](https://user-images.githubusercontent.com/2751996/99409682-a0688100-28bf-11eb-9896-71f6b1d4c260.png)

It appears that gnome-terminal updated their color palette, if that is relevant: https://gitlab.gnome.org/GNOME/gnome-terminal/-/issues/246

**Comment by dralley** [comment]
Also, there's this issue already filed with gnome-terminal https://gitlab.gnome.org/GNOME/gnome-terminal/-/issues/299

But the contrast issue is much worse with Arc theme, so even if they "fix it" (for Adawaita) it may still be a problem here.

**Comment by jnsh** [comment]
The text color palette is not coming from the GTK theme, so the changed color palette isn't really a theme issue.

If the default text color palette isn't working for you, you can switch to another built-in scheme, or create a new one to your preference. Enabling the "Show bold text in bright colors" option could be of some help also. Both options are available in the gnome-terminal profile preferences. You can also adjust the terminal background color for better contrast from the same location.

Only thing that could be done from the theme's side to improve the legibility with default colors, would be adjusting the background. Upstream [added](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2402) the `@text_view_bg` public color during this cycle, which is used for the gnome-terminal background, and is intended provide a better contrast in text views. This was implemented in Arc with https://github.com/jnsh/arc-theme/commit/2c726e439b1f157f9a2f54955e51a8c9900ff41a, but it simply uses the base background color currently, as there isn't any obvious predefined colors in the Arc palette to use in this context.

The plan is to improve this in the future, but since the `@text_view_bg` is currently only used in gnome-terminal (AFAIK), which also allows customizing the background color from its preferences in case anyone finds the current background problematic, I'm not considering this a high priority issue at the moment.

**Comment by jnsh** [comment]
https://github.com/jnsh/arc-theme/commit/d38aa4af9cfab88069756be9cba45ba0a21759e8 added darker background color for dark variant. I think that's really all that can be done in the theme, so I'm closing this.

Any additional suggestions for improvements in this area are always welcome.
