### ISSUE TITLE
Oval buttons in tootle

### ISSUE THREAD

**Issue by janebuoy** [jnsh/arc-theme#103]
![Screenshot from 2020-12-21 15-12-12](https://user-images.githubusercontent.com/11575641/102787274-1a999300-43a1-11eb-8953-f871810bb5e7.png)

- Budgie 10.5.2
- Tootle 1.0.0-alpha2 (flatpak)
- Arc-Dark (20201013 compiled)

thanks for maintaining Arc :)

**Comment by jnsh** [comment]
Thank you for the report. I've seen similarly oval button in `gnome-control-center`'s users tab as well.

My plan is to resync/rewrite the GTK3 theme based on current default GTK3 theme, hopefully during the first half of next year. That should probably address this, and number of other small issues that have emerged over the few years of insufficient maintenance. If it doesn't, I'll look at fixing this specifically.

Therefore there won't be immediate fix unfortunately (unless someone else wants to have a look), but this should get resolved eventually.

**Comment by janebuoy** [comment]
Oh yes, I knew I'd seen it somewhere before. I agree, it's not a priority. Rather filed this issue for completeness .

**Comment by jnsh** [comment]
Found a solution to this while working on GTK4. This worked at least in the gnome-control-center's user-tab, but let me know if the problem persists in Tootle.

Also, I only applied the fix for GTK 3.24 theme, since that's the only one I can test at the moment. If anyone is encountering the issue on older GTK3 versions, let me know and I can backport the commit.
