### ISSUE TITLE
Inconsistent hover/active indicator colors 

### ISSUE THREAD

**Issue by francoism90** [jnsh/arc-theme#128]
### Before submitting

- Ensure that the issue is present with the latest Arc-theme release, or latest git snapshot.
- Test whether the issue also appears with default themes (e.g. Adwaita for GTK and GNOME).
- Make sure you have built the correct theme versions for GTK 3, GNOME Shell and Cinnamon themes.
- Make sure the issue persists between restarts.
- For GTK 3 related issues, try clearing your user's `~/.config/gtk-3.0/gtk.css`, if it exists.

### Details

Please add the following information:
- Arch Linux
- https://github.com/francoism90/pkgs/blob/master/arc-gtk-theme-git/PKGBUILD

Unless this is a non-visual issue, always add screenshots to help describe your problem.

When clicking on the clipboard extension:

![image](https://user-images.githubusercontent.com/5028905/115513037-ed8fbb00-a282-11eb-9125-50052ea168d3.png)

When clicking on the Espresso extension:

![image](https://user-images.githubusercontent.com/5028905/115513177-11eb9780-a283-11eb-80a7-ff33f10db4fe.png)

Same actions performed on the default shell:

![image](https://user-images.githubusercontent.com/5028905/115513265-2760c180-a283-11eb-8662-95f17083e769.png)

![image](https://user-images.githubusercontent.com/5028905/115513293-3182c000-a283-11eb-80e5-b41d188956c8.png)

Not a big issue, thanks for this great theme! :)

**Comment by jnsh** [comment]
This seems to happen because the extension provides customized panel-button widget, which doesn't provide e.g. `:checked`or `:active` CSS pseudo class when the button is clicked. Therefore it only has the mouse-over `:hover` class, and is styled based on that.

This isn't apparent with the default shell theme, because they use identical styling for `:hover` and `:active`, `:checked` etc.

I'm fairly certain there's nothing that could be done from the theme's side to this. Either way it would be more appropriate to correct this to the extension itself, instead of applying workarounds to the theme.

Please report this as an issue to the extension.

**Comment by francoism90** [comment]
@jnsh Thanks for looking into this and explaining how it works. I'll try to report this to the extension repos instead. :)
