### ISSUE TITLE
Missing separator on confirmation dialog

### ISSUE THREAD

**Issue by ariflukito** [jnsh/arc-theme#13]
Hi,

There's a missing separator on this following dialog. Separator only appears on hover.

![Screenshot from 2019-11-13 15-12-51](https://user-images.githubusercontent.com/5508660/68732937-4b00f080-0629-11ea-8f1f-c8444dc37711.png)

Please add the following information:

- Distribution and version: Arch / GNOME 3.34.1
- Versions for the affected applications/desktops/tookits: <https://github.com/jnsh/arc-theme/commit/511728fe3d5dbfd884284fd2a0055320a83fa28a>

**Comment by jnsh** [comment]
Thanks for the report.

I've noticed this problem myself. There seems to be something odd going on with `.linked` button styling, which results in various relatively minor issues such as this one. Unfortunately the stylesheet for linked buttons is extremely complicated, and fixing it requires lots of investigation and possibly major reworking.

I'll definitely try to figure out a fix at some point, but it'll probably have to wait until I get some general gtk3 updates/upstream sync work done first.

**Comment by jnsh** [comment]
I looked into this, and it seems the missing separator was an intentional design choice from the original developer, instead of a bug that was introduced later. I tested the [original theme](https://github.com/horst3180/arc-theme) on ubuntu 16.04, and the buttons looked the same.

For that reason I'm a bit hesitant to changing this. My intention with this fork is to maintain the theme, and avoid any unnecessary changes to the visual design. The missing separator may subjectively appear a bit odd, but I don't think that's enough of a reason for changing the style.

**Comment by jnsh** [comment]
Closing the issue after giving it even more thought.

Seems that all horizontally linked buttons on the gtk3 theme are missing the separators so adding them here wouldn't make sense.

Similar buttons in gnome-shell's modal dialogs do have the separators, but since I think gtk3 should be the 'primary' theme that rest of the themes are based on, if anything, it would make more sense to remove the separators from the shell theme.

If anyone disagrees with this, feel free to add a comment preferably with some good reasoning.

Thank you for the bug report regardless.

**Comment by ariflukito** [comment]
I agree with you. As long as the design is consistent throughout, I'm happy with your decision. Thank you.
