### ISSUE TITLE
Install data not found

### ISSUE THREAD

**Issue by Zumiito** [jnsh/arc-theme#130]
Fedora 34 on GNOME40

When i run "meson install -C build/" it say "Install data not found. Run this command in build directory root."

any idea? mmm...

![cap](https://user-images.githubusercontent.com/65167650/116325433-6b435180-a7c2-11eb-8be8-9b6a21646411.png)

**Comment by jnsh** [comment]
The `meson install` fails because the `build/` directory doesn't exist, since the `meson setup` command which would create that directory failed with an error, because it couldn't determine version for the cinnamon theme. 

If you had cinnamon istalled on your system the version should have been determined automatically. Alternatively you can either set the cinnamon version manually or disable the building of cinnamon theme altogether with build options to the `meson setup` command. See [build options](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md#build-options) section in INSTALL.md.

**Comment by Zumiito** [comment]
Ok, done and "meson install" worked

"meson setup --prefix=$HOME/.local -Dthemes=gnome-shell,gtk3 -Dvariants=darker,dark -Dgnome_shell_vesion=40    build/"

one question, i use GNOME 40, wouldn't it be gtk4?

**Comment by jnsh** [comment]
> one question, i use GNOME 40, wouldn't it be gtk4?

GTK4 support isn't available for Arc-theme yet. Once it lands, you'd likely want to add it to the list of built themes as well. If you build the theme yourself, it's up to you to decide which themes you want/need. Nothing is broken without GTK4 support, the theme simply isn't available for GTK4 applications, and they fall back to using the default Adwaita theme.

**Comment by Zumiito** [comment]
Ok, great job and thanks a lot!
