### ISSUE TITLE
Fonts too small in GNOME Shell 

### ISSUE THREAD

**Issue by antonvalletas** [jnsh/arc-theme#15]
### Details
Hey, just updated from the default arc-gtk-theme package to yours, seeing that arc-gtk-theme was not maintained and was not going to get updated to match Gnome 3.36. 

After updating, and setting the theme, I noticed a few things:
1. Fonts on search panel, and system tray (and generally all over the shell) are extremely small, however, everywhere else, they are completely ok (I have not changed my font config in years so rest assured a font config change is not the problem), as if after installing the AUR package, the shell font has been hardcoded to something else insted of following whatever is set in gnome-tweaks:

[Imgur](https://i.imgur.com/uKPRY2j.png)
[Imgur](https://i.imgur.com/gZHE3M9.png)

<del>2. Fonts on Chrome, have been hardcoded to this horrible weird font on webpages that don't set their own font (I suppose) such as github and chunks of other sites. Again, it is not following my system fonts, and I cannot change it. </del>

(This somehow fixed itself after rebooting)

Please add the following information:

- Distribution and version: Latest Manjaro Unstable (Kernel 5.5) (Everything updated)
- Versions for the affected applications/desktops/tookits: Latest AUR package at the time of writing

**Comment by jnsh** [comment]
Thank you for the report.

The gnome-shell font size is the same that it's always been since the [original project](https://github.com/horst3180/arc-theme), and looks correct on your screenshots. The project `arc-gtk-theme` package on Arch repos were built from, had increased the font size at some point IIRC.

The gnome-shell font size has always been hardcoded on the theme (even for the default shell theme), and can't be changed via gnome-tweaks. Prior to GNOME 3.36, the font-family has also been hardcoded to the theme, but now it can be finally set to follow the global `interface` font family setting (again, the font _size_ still is, and has to be hardcoded to the shell theme).

I can agree that the default font size seems quite small for most common font families. The reason I've been hesitant to changing it, is that the theme was originally designed with specific font (Futura Bk bt) in mind, and I don't want to break the design in respect for the original author, and anyone who prefers the original style (I've explained my views on this with more detail on [this](https://github.com/arc-design/arc-theme/issues/275#issuecomment-555751340) post).

Now that the font family can be changed for the shell theme, I will probably look at changing the size to more sensible default at some point. However, this is not quick task, as it requires thoroughly re-adjusting font-sizes for all the elements of the theme, and since there are workarounds for adjusting the size, this is not top priority for now.


As for the workarounds:

The simplest way to change the shell font size, is to adjust the font scaling factor in e.g. gnome-tweaks. The caveat is, that this changes the font size everywhere, so you need to adjust every font size setting again after changing the scaling. If you want to use same font size for shell and applications, set the interface font size to 9, and adjust the scaling to you liking after that.

There is a chance, that changing the scaling results in minor issues within the theme. If you notice anything, open an separate issue, as these can usually be fixed.

If the font scaling workaround doesn't work for you for some reason, you can also try adjusting the `$font-size` variable at the top of `_common.scss`, and rebuilding the theme yourself. This however, doesn't adjust the font-size for every shell element, at this time.


I've also considered adding a build time option for changing the font size, but this does seem an odd option, since it would only affect the shell theme, and nothing else. Either way, I probably wouldn't implement this until I've had change to completely revamp the build system anyway.

If anyone has other ideas, or workarounds for this, let me know.

**Comment by jnsh** [comment]
I took the liberty of changing the title of this issue to be more specific to the shell font size, as I'd imagine there are others looking for a solution for this problem.

**Comment by antonvalletas** [comment]
Oh, so the people who maintained it after the original author were the ones who made the fonts bigger then? That makes since, since Futura is kind of a "special" font family, which could look bigger even at size 9. Great to know this then, I will try changing to Futura font to see how it looks. 

Feel free to close this, as this is not technically an issue then :) Thanks!

**Comment by jnsh** [comment]
> That makes since, since Futura is kind of a "special" font family, which could look bigger even at size 9.

Indeed, the screenshots in [README.md](https://github.com/jnsh/arc-theme/blob/master/README.md) are using the Futura Bk bt at 9pt, and it looks much larger compared to e.g. Cantarell or Droid Sans.

I'd prefer to keep this issue open until I revamp the fonts, to keep this discussion more discoverable. I'm sure other people might be wondering about this, and I explained the reasoning and possible workarounds above.

Either way, even if this is just a minor usability/aesthetic issue, it's still something that should be improved if possible. Don't hesitate to post an issue if you notice anything that could be improved, no matter how minor :)

Thanks again for understanding, and the issue report.

**Comment by ksdrummer** [comment]
Hello, I'm was about to post an issue to point out this font size problem but it has already been done here.
First of all : Thank you so much to keeping this theme alive, it is the best I ever found !

I too tried to use Futura font but it looks too small too. I understand all what you said and respect your choice, but I'm very frustrated to be so close to have the perfect theme. (The original theme was looking amazing in gnome 3.34 but broke in 3.36)

Anyways, I'm just here to say it is a bit better when using the "ubuntu medium" font.

Thank again for your great job !

If I find some time, do you mind if I fork your theme and maintain a version on the AUR with a bigger font ?

**Comment by jnsh** [comment]
There's nothing stopping you from forking the theme, as long as you abide by the license.

As I mentioned above, you can achieve perfect font size for your preference by using the font scaling setting. I understand that the current default size is non-optimal for many users, but either way, since the font-size has to be hardcoded to the theme, the size will never be perfect for _all_ font families and personal preferences.

I will address this issue in the future as promised.

**Comment by Alexander-Huang** [comment]
> There's nothing stopping you from forking the theme, as long as you abide by the license.
> 
> As I mentioned above, you can achieve perfect font size for your preference by using the font scaling setting. I understand that the current default size is non-optimal for many users, but either way, since the font-size has to be hardcoded to the theme, the size will never be perfect for _all_ font families and personal preferences.
> 
> I will address this issue in the future as promised.

The gnome-shell.css starts with this piece of code:
```
stage {
  font-size: 9pt;
  color: #D3DAE3; }
```
I changed the font-size into this
```
stage {
  font-size: 9.6pt;
  color: #D3DAE3; }
```
Then everything looks better.
I compared this file with the old one from archlinuxcn repo.Its font size is 10pt.But with different fonts,this looks bigger using 10pt font.
Editing font scaling would bring a new icon of Disabled options.
Otherwise,why do you put the themes in /usr/local/share/themes by default?It took me a long time to find where the themes are...(￣ε(#￣)☆╰╮o(￣皿￣///)
And I really appreciate your continued maintenance of the arc theme.Thank you very much.

**Comment by jnsh** [comment]
> Otherwise,why do you put the themes in /usr/local/share/themes by default?

I'm not putting the themes anywhere. You, (or the packager) should set the install prefix for `autogen.sh` when building, as instructed on [INSTALL.md](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md). Otherwise the default prefix (usually `/usr/local`) is used.

Please keep the discussion here on topic. If you have problems not related to the gnome-shell fonts, open a separate issue.

**Comment by Alexander-Huang** [comment]
> > Otherwise,why do you put the themes in /usr/local/share/themes by default?
> 
> I'm not putting the themes anywhere. You (or the packager), should set the install prefix for `autogen.sh` when building, as instructed on [INSTALL.md](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md#build-and-install). Otherwise the default prefix (usually `/usr/local`) is used.
> 
> Please keep the discussion here on topic. If you have problems not related to the gnome-shell fonts, open a separate issue.

okay

**Comment by jnsh** [comment]
Sorry about the delay with this.

The default gnome-shell font size is now increased from 9pt to 11pt in accordance with upstream.

Please report back if you notice anything looking wrong or ugly after this, with or without additional font scaling applied.

**Comment by JonathanHolvey** [comment]
@jnsh thanks for your detailed thoughts on this topic.

As I've been using the Arc shell theme for a number of years, the new 11pt font size seems very large. I understand the motivation to change the font size to match the default size used in Gnome, however, since it's hard-coded in the theme and doesn't follow the interface text setting, choosing 11pt is as arbitrary as any other value.

It makes sense to have the shell text match the default settings of Gnome, but this should be done *visually* not *numerically*. What I mean by this the size should be chosen so that the fonts look correct, rather than by matching the value directly.

I personally feel that the original design got that balance about right, however, as you stated in the comment you [linked above](https://github.com/arc-design/arc-theme/issues/275#issuecomment-555751340), design is subjective, and it's impossible to please everyone.

**Comment by jnsh** [comment]
@JonathanHolvey Thank you for the feedback.

As explained above, you can change the font size exactly to your personal preference via the font scaling setting in gnome-tweaks, or by editing the source code yourself.

There's no visually "right" numerical value for the font size, as different font families look different, and there are different personal preferences. Using a larger default value is better, since increasing the font scaling value brings up the panel Accessibility menu, and this doesn't happen when the scaling is decreased. Also I think it makes more sense to base the default size to upstream design, instead of some arbitrary value that "seems right" to some.

If you can point out any actual issues from the font-size change, or have any further suggestions for improvements in this area, please open a separate issue.
