### ISSUE TITLE
Volume and brightness thumbs (circles) aren't present on gnome-shell

### ISSUE THREAD

**Issue by blinxio** [jnsh/arc-theme#167]
Volume Thumb (Circle) and the Brightness Thumb (Circle) aren't present in all variants of the theme. The default behavior of Adwaita is different and the thumbs are present.

- Ubuntu 21.10.
- gnome-shell
- Compiled manually
- Arc-Dark-Sold

![image](https://user-images.githubusercontent.com/13114412/147511450-0ea67cee-074d-41d1-b33c-0e49d623b409.png)

**Comment by jnsh** [comment]
Sorry, but this is intentional and part of the original design, and therefore won't be changed.

Also it may be worth mentioning, that this doesn't affect usability in any way, since you can click anywhere on the menu item to adjust the slider (at least with newer shell versions, I'm not sure if that's always been the case).
