### ISSUE TITLE
Strange border in cinnamon

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [jnsh/arc-theme#169]
- Distribution and version: LMDE 4 (debbie)
- Versions for the affected applications/desktops/toolkits: Cinnamon 5.0.7
- Installation method (package or compiled manually): compiled manually
- Arc-theme version: 20211018 (latest so far)

For some reason, there is this strange border in the apps names. It's  happens just in opened apps.

![](https://i.ibb.co/ZMW1VnG/2022-01-01-19-11.png)

Otherwise works fine (Whale is not opened):

![](https://i.ibb.co/LPyW6GR/2022-01-01-19-15.png)

**Comment by jnsh** [comment]
Thanks for the report.

Which cinnamon panel applet is that?

**Comment by ViniciusBRodrigues** [comment]
Hi, it's: grouped-window-list@cinnamon.org

**Comment by jnsh** [comment]
Well I tested it myself, and can't reproduce the issue. Also, the grouped window list shouldn't look like that on 5.0 with this theme, e.g. the line underneath the icon should be blue and the background should change on mouseover. So something seems to be wrong with your installed theme.

Since you compiled the theme yourself, are you sure it was built for the correct cinnamon version? Please check your `meson setup` output, or use `cinnamon_version=5.0` meson build option to force the correct version.

Another thing you could check is that you're not accidentally using e.g. outdated version of the theme installed trough your distribution's package manager, instead of the one you  built yourself.

**Comment by ViniciusBRodrigues** [comment]
I see! I compiled again and seems to work fine. The problem is: I can find the theme in the desktop option. Bute there is no arc theme in the window border or control. But I think that is a mint bug.

**Comment by ViniciusBRodrigues** [comment]
Many thanks! Great job!

**Comment by jnsh** [comment]
> Bute there is no arc theme in the window border or control. But I think that is a mint bug.

They should both be there, if you built the metacity theme (window borders) and gtk3 theme (controls).

**Comment by ViniciusBRodrigues** [comment]
Now it's fine. I think that my cinnamon theme config section it's kind of buggy somehow. But anyway, I noticed that keepassxc is not respecting the theme:

![](https://i.ibb.co/519HQLK/2022-01-02-07-18.png)

**Comment by jnsh** [comment]
Sorry, but this is nothing to do with Arc anymore, and I'm not providing support for general theming questions. Please look for help from e.g. your distribution's support channels.
