### ISSUE TITLE
Focused application always highlighted on dash to dock

### ISSUE THREAD

**Issue by xTeixeira** [jnsh/arc-theme#17]
I have a bug on Arch Linux with Gnome 3.36 where the focused application is always highlighted on the extension dash to dock with this theme on. I'm including a screenshot.

![Screenshot from 2020-03-14 19-50-08](https://user-images.githubusercontent.com/7085361/76691771-5858d680-662d-11ea-8d01-63ebe0ec1994.png)

This, of course, doesn't happen with adwaita selected as shell theme.
Edit: it might be worth to point out I'm using this branch of dash to dock: https://github.com/3v1n0/dash-to-dock/tree/gnome-3-36
which is not officially released yet so it might be a problem on their end.

**Comment by jnsh** [comment]
Thanks for the report.

This is intended behavior. The dash to dock extension adds focused state for the focused application's icon, but all themes don't provide specific styling for it (e.g. Adwaita doesn't provide theming for 3rd party extensions). However, the focused icon is always highlighted if you enable dash to dock's built in theme.

Since this is a dash to dock feature, I'm not in favor of removing the styling. If you can clarify what you see as an issue with this, I can try to think if there were any way to improve the situation?

The highlight styling was added in https://github.com/jnsh/arc-theme/commit/df7c6483bcbc49a7b8c3415de2b54dfd795a55d2. If nothing else works, you can always remove those lines by hand and recompile the theme yourself.

**Comment by xTeixeira** [comment]
Not necessarily an issue for me. I just assumed it wasn't intended since it doesn't happen in adwaita.

Thanks for the clarification, I'll close this.
