### ISSUE TITLE
Can I get the window border back?

### ISSUE THREAD

**Issue by AngryPhantom** [jnsh/arc-theme#173]
Hello,

First of all, I don't know what package to blame, but in previous stable Debian 10 (Buster) I had a thin black border around windows. Something like this: http://0x0.st/oX9J.png
Now I've installed the new stable Debian 11 (Bullseye) I have this: http://0x0.st/oX9t.png

It's pretty annoying because when windows overlap it's difficult to tell which one is which. I have to choose the other theme like Numix for window borders to fix that.
I don't know why it's like that. Probably some new versions of MATE and its window management, metacity, whatever, I'm not sure.

Could you please tell me where should I edit the code in your theme to bring that border back?

Probably not an issue, so I will close it if there is some .css fix for that.

Thank you in advance.

**Comment by jnsh** [comment]
Hello,

I think what's happening is that MATE's window manager [marco](https://github.com/mate-desktop/marco) switched to using version 3 metacity theme between the versions shipped with Buster and Bullseye (since marco 1.21.1 if I'm not mistaken). The version 3 Arc metacity theme had some differences compared to older metacity theme versions, which probably explains this.

I've since added a distinct dark outer border for the Arc-Dark/Arc-Darker metacity themes in version 20220102, and I think that should solve your issue.

If the problem persists with the latest version, or if you have any other issues, let me know and I'll try to figure out a solution.

**Comment by AngryPhantom** [comment]
Thank you very much! I took the version from Debian Testing (20220105) and now it's fine. Have a nice day! I'm closing the issue.
