### ISSUE TITLE
Initial window close button colour issue

### ISSUE THREAD

**Issue by jnqnfe** [jnsh/arc-theme#174]
Hi,

I'm using Debian Sid with the arc theme package installed & enabled. I've noticed a small but irritating bug with the Qt-based interface of the in-development version 4.0 of VLC (to which I'm a contributing developer). This bug only occurs under the arc theme not the default adwaita theme, so I'm assuming at this point that it's an arc theme bug.

Before I get to the bug itself, let me just quickly demonstrate what the close button looks like currently and how it differs from most apps.

So, for most apps like gnome terminal the close button looks like this:
![vlc_close2](https://user-images.githubusercontent.com/33935229/154319329-d543d6cf-bf3c-4b6e-aeed-cfbe376605eb.png)

In VLC 4.0-dev, with the titlebar option disabled (enabling CSD mode), it instead currently looks like this: 
![vlc_close1](https://user-images.githubusercontent.com/33935229/154319326-27445106-f3c3-48ee-a023-85632ab4b549.png)

That itself is not the bug (I presume that's a deliberate choice the qt-redesign people have made, or an issue with qt-theming).

The bug itself is as follows...

Expected behaviour: The close button should start off grey and only change to red whilst the cursor is over it.

Actual behaviour: When the window initially loads, the background of the close button starts off red (as shown), then once the cursor moves over the window, it changes to grey. If when the window opens the cursor is already over the window (but not its close button) the button is shown very briefly in red before changing to grey. In both cases this is rather irritating. (Moving the cursor over the close button changes it to red whilst the cursor is over it as expected).

Presumably the theme is incorrectly specifying the initial colour as red instead of grey?

**Comment by jnsh** [comment]
The theme does not, and can not specify initial color for anything. Only for active/selected/mouseover and so on...
Also Arc doesn't apply any kind of color for the window control buttons, but the buttons are drawn with pixmaps.

The initial color color issue has nothing to do with the theme, so this is an issue with either VLC or QT.

The button colors themselves could _possibly_ be changed, if they are pulled from the active GTK theme by VLC/QT. I understand that is not the issue here, but that is the only thing that maybe could be done from the theme's side.

**Comment by jnqnfe** [comment]
Okay thank you, I'll report it on the VLC tracker instead then. :)
