### ISSUE TITLE
Electron app has weird offset on its menu bar

### ISSUE THREAD

**Issue by naiiren** [jnsh/arc-theme#188]
environment:
- windowing system X11
- Ubuntu 22.04 new multi-tasking, Gnome 42
- all arc-theme in latest version 20220405-1

Once an electron app launched in split screen view and not focued on, there will be a weird offset on its menu bar:

![image](https://user-images.githubusercontent.com/16153455/167288660-4297c642-02f7-4cdc-879f-d49c6c5610fb.png)

It's tested that the bug occurs in apps built with electron of various versions using arc-theme, but everything is okay when using the default theme.

**Comment by jnsh** [comment]
Thank you for the report. I'm experiencing this same issue as well.

Unfortunately this is rather difficult to solve, since nothing within the theme should directly cause this. More likely there's some bug in Mutter, that happens to get triggered by Arc-theme, and not with Adwaita. The solution is to just blindly try changing anyhing that's different in Arc decoration styling to match Adwaita, and test if that happened to fix this. That will take some time, and there's a chance that you won't find the cause anyway..

Nevertheless, I'm hoping to have a look at this at some point.

**Comment by naiiren** [comment]
I modified /org/gnome/mutter/draggable-border-width to the custom value 25 rather than 10 the default, and the problem is fixed.

**Comment by jnsh** [comment]
> I modified /org/gnome/mutter/draggable-border-width to the custom value 25 rather than 10 the default, and the problem is fixed.

Thank you! This is actually very helpful discovery, as it suggests that this may have something to do with the window resize area size. I still didn't notice anything obvious that could result in this behavior with Arc, but I keep on looking.

At least the draggable-border-width dconf tweak serves as a workaround, if there's no other solution.

**Comment by j-james** [comment]
I notice this on a wide variety of non-Electron apps: especially noticably, kitty under XWayland and thunar under wayland. It disappears after resizing a window not in focus. 

Changing the draggable-border-width also fixes it for me, thank you :smiley:
