### ISSUE TITLE
[Question] Arc-Darker variant / how display separator on gnome menu ?

### ISSUE THREAD

**Issue by acantepie** [jnsh/arc-theme#199]
Distribution: Arch
DE: Cinnamon 5.4.2
Installation : AUR https://archlinux.org/packages/community/any/arc-gtk-theme/

Hi, i am using Arc-Darker variant of theme, is it possible to easily modify the theme to make the separators appear on gnome menu ?

**Comment by jnsh** [comment]
I'm not sure what menu you'd like to modify, since you mentioned _gnome_ menu, and _cinnamon_ DE. Either way, it is certainly possible to modify the theme, but depending on your skills, it may not be that easy.

The recommended way would be editing the source files in cloned git repository, e.g. in this case I'd imagine you'd want to edit the `*.scss` files in either `common/cinnamon/<version>/sass` or `common/gnome-shell/<version>/sass`. Then you can save your changes in a git commit, and merge any future updates from the original repo. You could also save your changes to a patch file using `git diff`, and apply that patch e.g. in an AUR package.

I think another possibility would be creating a new gnome-shell/cinnamon theme that imports the installed Arc-theme files and then applies your CSS changes after that, although I've never tested this myself.

You can also edit the installed `.css` files, but then your changes will be overridden with every update, so this is not a good option.

**Comment by acantepie** [comment]
@jnsh 
Thx for your answer.

I have taken a screenshot with "Arc-Darker" variant:
![screen-archie-cinnamon](https://user-images.githubusercontent.com/12775815/190879799-003da44c-0948-436b-9be8-9d144fc4f759.png)

I have the same problem with all arc theme variant.

I have found two files with name "cinnamon.css" : 
```
./Arc/cinnamon/cinnamon.css
./Arc-Dark/cinnamon/cinnamon.css
```
which one should I change ? I have tried to edit rules .separator of both (-gradien-end: black) unsuccesfully ...

Moreover i have found two files "menu-separator.svg" :
```      
./Arc/cinnamon/common-assets/menu/menu-separator.svg
./Arc-Dark/cinnamon/common-assets/menu/menu-separator.svg
```
It wouldn't be these svgs that are used ?
Can you help me ?

**Comment by jnsh** [comment]
There are multiple separator CSS classes within the Cinnamon theme for different elements of the desktop. I believe menu separators are styled with `.popup-separator-menu-item`, although I didn't check this.

The `menu-separator.svg` files are not used in the theme, so no need to edit those.

**Comment by acantepie** [comment]
@jnsh 
i have edit the rule `.popup-separator-menu-item` on file `/usr/share/themes/Arc/cinnamon/cinnamon.css`, i can see the separators on the menu of cinnamon panel :

```
.popup-separator-menu-item { background-color: rgba(92, 97, 108, 0.4); -margin-horizontal: 1em; height: 0.1em; }
```

But i can't find css rule for desktop and app menu separators

**Comment by jnsh** [comment]
@acantepie Sorry, I'm not extremely familiar with the cinnamon stylesheet, but `.popup-separator-menu-item` would seem most logical for desktop menus. Only other option that I can think of would be it using the generic `.separator` style class for some reason, but changing that should affect other areas of the theme as well.

Either way, since this isn't really an issue with the theme, but a support request for editing the cinnamon theme, I'm gonna close this. Feel free to continue discussion nevertheless, if there's anything to add. However at this point my guesses/investigation won't be any better than yours, so it may be more fruitful to ask advice from cinnamon community.
