### ISSUE TITLE
delete dialogue 

### ISSUE THREAD

**Issue by clumsyfingers** [jnsh/arc-theme#20]
firstly thanks for keeping arc alive!
secondly, this has been bothering me for ages https://i.imgur.com/0CU4TWB.png
themes without that top bar look so much better. can something be done?

thirdly, im dreaming about a compact version. but a lot of work i guess

**Comment by jnsh** [comment]
Thank you for the report.

What WM/Desktop and application is the delete dialog from?

There are no plans for variants with major differences in styling, as there's no easy way of making this configurable for every supported desktop and toolkit. I think such variants should be developed as separate forks.

**Comment by clumsyfingers** [comment]
hi, its on gnome but is the same also on budgie. its just the standard delete dialogue in nautilus
here its shown with plata, qogir and arc https://imgur.com/a/1X4Jdcd

**Comment by jnsh** [comment]
I see. Apparently the bar isn't visible on Adwaita either, so it makes sense to follow upstream on this.

I'll fix this at some point, but it's not the highest priority at the moment.
Pull requests are welcome, if anyone wants to help with this.

**Comment by jnsh** [comment]
Bit of a status update.

I investigated this awhile ago and it seemed that the modal dialog titlebar styling was intentional design choice from the original designer, and already present in the first version of the theme IIRC. Therefore I wouldn't like to remove it. Additionally it seemed that changing this would require quite big reorganizing of the theme stylesheet.

IMHO the biggest visual issue with the current design is that there's no padding between the titlebar and the modal dialog message, which makes it look unbalanced. I was thinking about merely adding some padding there, rather than removing the titlebar altogether.

Let me know if you have any feedback on this, or any other suggestions.

**Comment by jnsh** [comment]
I've added some padding between the dialog titlebar and content in https://github.com/jnsh/arc-theme/commit/a394a760a24a8d156e9fbac485b3d7991420338c, which IMHO looks much nicer:

![Screenshot from 2022-02-17 15-58-01](https://user-images.githubusercontent.com/39574454/154496786-4d52e215-69b9-4fc4-be74-13a47df5d4a9.png)

If anyone still wants to get rid of the dialog titlebar, it can be done with simple CSS injection, e.g.:
For GTK3, `~/.config/gtk-3.0/gtk.css`:
```
messagedialog .titlebar {
  background-color: @theme_bg_color;
  border-bottom: none;
  box-shadow: none;
}

messagedialog box.dialog-vbox.vertical {
  padding-top: 0;
}
```

For GTK4, `~/.config/gtk-4.0/gtk.css`:
```
window.dialog.message .titlebar {
  background-color: @theme_bg_color;
  border-bottom: none;
  box-shadow: none;
}

window.dialog.message box.dialog-vbox.vertical {
  padding-top: 0;
}
```

Closing.
