### ISSUE TITLE
Some windows are undreadable with the darker variants

### ISSUE THREAD

**Issue by PauloGDPeixoto** [jnsh/arc-theme#205]
- Distribution and version: Fedora 37
- Versions for the affected applications/desktops/toolkits: ClearPass OnGuard (all versions)
- Installation method (package or compiled manually): package manager
- Arc-theme version:  20221218-1

The Dark/Darker versions are not readable in some windows, this is specially noticiable in ClearPass OnGuard, which I use, it's specially hard when the window is in focus:
Focus:
![image](https://user-images.githubusercontent.com/20384915/217585233-521bfd69-e9ba-43cd-a076-6c787d8ef707.png)

Not in focus:
![image](https://user-images.githubusercontent.com/20384915/217585416-fdb12d52-061e-4fe8-aee8-8e6f6b076098.png)

Can we please use the same colors from arc (or arc lighter) for these fonts?

**Comment by jnsh** [comment]
The darker variant _is_ using text colors from light variants, when it is against light background.

I can't tell from your screenshots whether clearpass is sing GTK toolkit, and since it is proprietary software I have no way of knowing what they are doing with their UI. This theme only supports GTK, and if some application tries to parse the GTK theme to their UI and it looks broken, there is nothing I can do about it.

If they are using GTK, there is a chance that they are using the toolkit in some unusual way, that the theme isn't prepared for (the darker variant implementation is rather hacky so this would not be a surprise). However, in such case theres still nothing I could do to fix this, since the program is closed source and there would be no way to find a workaround. 

Only thing you can do in such situation is to not use the theme with broken looking applications.

If there's another program that looks broken to you, and could be more possible to investigate, let me know.

**Comment by PauloGDPeixoto** [comment]
I understand, thank you for the detailed explanation.
