### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by webaake** [jnsh/arc-theme#24]
Can't build on updated Xubuntu. Installed sassc, optiping and more. Build environment already installed. (Built Audacity yesterday for example). I'm on Xfce 4.14 on Xubuntu 18.04. (Not 4.12)

Config: 
./autogen.sh --prefix=/usr --disable-light --disable-lighter --disable-plank --disable-unity --disable-cinnamon --disable-gnome-shell
 Error in config: "...Building GTK3 theme 3.22
checking for inkscape... /usr/bin/inkscape
checking for optipng... /usr/bin/optipng
checking for sassc... /usr/bin/sassc
checking that generated files are newer than configure... done
configure: error: conditional "GNOME_SHELL_3_32_OR_NEWER" was never defined.
Usually this means the macro was only invoked conditionally."

Result: No target for make install.

What have missed? I followed the build instructions here on GitHub.

**Comment by jnsh** [comment]
Thank you for the report.

I don't think you have missed anything. Apparently the build fails currently, if you use the `--disable-gnome-shell` option for `autogen.sh`, due to my mistake on the build system.

I'll look at fixing this ASAP. In the meantime, the build should finish if you omit the `--disable-gnome-shell` flag. Sorry for the confusion.

**Comment by webaake** [comment]
I'm very thankful for your work! I was sitting at home doing nothing and compiling is always a nice sport. Never compiled a theme before! Thanks, I will try again!

**Comment by jnsh** [comment]
This should be now fixed. Thanks and sorry once again.

**Comment by webaake** [comment]
Configured and built now ! With "disable-gnome-shell". I'm on Xfce so dont have gnome-shell. Thanks! Looks very nice!
