### ISSUE TITLE
Can we have a tagged release?

### ISSUE THREAD

**Issue by WhyNotHugo** [jnsh/arc-theme#27]
Hi. I greatly appreciate the huge effort you've taken into maintaining this very popular theme. I'd been using the original for years, and I'm happy to find this fork has fixed so many tiny things that I kept noticing broken.

There's interest in replacing the Archlinux package of `arc-theme` to point to this new fork. I'm sure other distributions will want to follow suite as well now that the originally is formally "archived".

Would you mind making a proper "release"? It doesn't need to be called "v2.0" or anything, I'm guessing that a simple git tag with the current date would do. The current master seems great too; it's working great for so many people. Downstream packagers would love to just use that as a "formal" release for distribution packages, and then this sweetness can trickle down to many more users with greater ease :relieved: 

Again, many thanks for your work and contribution to the community! :pray:

**Comment by jnsh** [comment]
Please see https://github.com/jnsh/arc-theme/issues/18, and continue discussion there if you have anything to add.

There's still one or more glaring issues that I don't want to have in a "stable" release, and are non-trivial to address properly. I'm trying to get those sorted, and getting a release out is the main priority at the moment.

Otherwise, the `master` branch should be stable enough for building distribution packages, if you can't wait.
