### ISSUE TITLE
Redesign workspace switcher

### ISSUE THREAD

**Issue by fabirovsky** [jnsh/arc-theme#36]
Hello, nice theme!

But what about to make workspace workspace switcher more smaller, like original Gnome Shell has? 
![comparison](https://user-images.githubusercontent.com/20482699/79751968-2ddcf600-831c-11ea-82bc-55bcd7bb56eb.png)
As you see original is smaller, simpler(without icon) and looks more clear.

**Comment by jnsh** [comment]
Thank you for the suggestion.

Arc gnome-shell theme was originally based on GNOME ~3.14 theme. Back then the workspace switcher was almost double the size compared to current default shell theme. I have already reduced the switcher size from that in commit https://github.com/jnsh/arc-theme/commit/9d91efcb4df797362401793f2eb0725b7d86a683.

I think whether the switcher size should be reduced even further, or the arrow icon removed is a subjective matter. I can see how one might prefer your suggested changes, and someone else might prefer the old/current design.

Since I'm not the original designer of the theme, and the old design has been in use for years, I'd prefer to avoid subjective stylistic changes such as this, unless there's actual issues or otherwise very good reasons for the change.

I think the aforementioned commit was a good compromise for reducing the size while retaining the old design, and I'd prefer to not change it further, unless there are other reasons for the change that I missed.

**Comment by jnsh** [comment]
Closing, as there hasn't been any additional feedback for over a month.

If anyone else has good ideas for improving the workspace switchers, or problems with the current design, you can add additional comment or open a new issue.
