### ISSUE TITLE
gnome-shell more subtle menu dividers (?)

### ISSUE THREAD

**Issue by mbacou** [jnsh/arc-theme#38]
`arc-theme_20190917+git20200328-2_all.deb` on Ubuntu 19.10, Gnome 3.34.2

Wondering if the current menu dividers (white lines) could be modified to look more subtle (e.g. inset dotted, etc.) and have 100% width? I'm not a fan of the new look, too busy and take on too much vertical space.

This is likely personal preference, but others might weigh in as well!

![image](https://user-images.githubusercontent.com/260325/80284166-b7be0200-8714-11ea-830c-69434a635363.png)

**Comment by jnsh** [comment]
The separator line should be invisible. See my reply here: https://github.com/jnsh/arc-theme/issues/37#issuecomment-619399842.

I'm thinking of reducing the height of the separators at some point though, but I think it'd be best to do coherently for all the themes at once, so that requires some more thought.

**Comment by mbacou** [comment]
Got it, I figured this could be a version mismatch all right.
