### ISSUE TITLE
gnome-shell: Incorrect row spacing in calendar popup menu when week numbers are displayed

### ISSUE THREAD

**Issue by drakkar1969** [jnsh/arc-theme#4]
There is a small visual glitch in the calendar dropdown when week numbers are displayed:

| Without week numbers | With week numbers |
| --- | --- |
| ![calendar-bug-normal](https://user-images.githubusercontent.com/18715287/59962609-080e7700-94e8-11e9-8e2f-9877f796e674.png) | ![calendar-bug-weeks](https://user-images.githubusercontent.com/18715287/59962612-0fce1b80-94e8-11e9-83bb-fcad4b068cfc.png) |

The day selector is elongated vertically, and the spacing between calendar rows is increased.

For comparison, this is what the calendar with week numbers looks like with the default shell theme:

![calendar-default](https://user-images.githubusercontent.com/18715287/59962621-3e4bf680-94e8-11e9-955b-98177bd32052.png)

This issue can be fixed by reducing the top/bottom margins of the week number boxes:

```scss
.calendar-week-number {
  ...
  margin: 3px 6px;
  ...
}
```

With this fix, the end result looks like this:

![calendar-fixed](https://user-images.githubusercontent.com/18715287/59962678-e5309280-94e8-11e9-8096-58517a5a334a.png)

I can submit a PR if helpful.

On a more general note, there are a few visual inconsistencies in the gnome-shell theme that I would like to flag (most of which are either carry-overs from horst's theme or consequences of the default shell theme being transposed to Arc, rather than issues with this particular repo).

Would you prefer that I file them as issues, or would you prefer PRs to be submitted?

**Comment by jnsh** [comment]
Thank you for reporting.

The glitch is not present with the default Arc shell theme font size. I'm assuming you have increased the font size by increasing the "Scaling factor" in tweak-tool's "Fonts" pane, or by equivalent dconf key, or by some other means?

Regardless of the text scaling, this is still a valid issue, as the theme should look correct with any scaling factor.

Your proposed solution seems to change the alignment week numbers inside their container, and in relation to the date numbers (these are the screenshots you posted, before the magin change on the left, after on right):
![calalign](https://user-images.githubusercontent.com/39574454/59969235-a5ea5c00-9551-11e9-9403-b5606ee56317.png)

The top and bottom padding for the "week-number-box" don't have to be equal (with default font size, the top padding is 8px and bottom 7px), but if there's a difference, I think the top padding should be larger than bottom. The more important thing is that the week numbers and date numbers should be aligned to either the vertical center line, or font baseline. 

Note that I didn't do any testing with the code, and this is solely based on the appearance in your screenshots. It's possible that the alignment can't be perfect, but the "after" alignment seems odd, which suggests that that changing the vertical padding may not be the right solution, and could result in other glitches.

I compared the SCSS between Arc and the default shell theme briefly, and changing the `.calendar-day-base` to use `em` instead of `px` for `width`, `height` and `border-radius` might be better approach, and should at least fix the elongated `calendar-today` badge. Even if that didn't fix the issue, this would be a good thing to change as it would be more consistent with upstream.

> Would you prefer that I file them as issues, or would you prefer PRs to be submitted?

This is up to you, but If there's some larger work, or something you're not sure about or that might be "controversial" change, it may be better open an issue so that it can be discussed beforehand.

**Comment by drakkar1969** [comment]
Should have remembered that I had changed the text scaling factor in dconf (I have it set to 1.25).

From your comments, I see why just changing the margin in `.calendar-week-number` is not the best solution.

I tried changing the `width`, `height` and `border-radius` properties in `.calendar-day-base` to use `em` (with the same values as the default shell, i.e. 2.4em, 2.4em and 1.4em respectively). While this is an improvement, it does not fix the issue completely:

| Scaling factor = 1.0 | Scaling factor = 1.25 | Scaling factor = 1.5 |
| :--- | :--- | :--- |
| ![calendar-arc-1](https://user-images.githubusercontent.com/18715287/59978774-6dde2a00-95e0-11e9-8d5b-02eed56c2578.png) | ![calendar-arc-1 25](https://user-images.githubusercontent.com/18715287/59978777-78002880-95e0-11e9-9af9-aa19f90dc8e6.png) | ![calendar-arc-1 5](https://user-images.githubusercontent.com/18715287/59978781-81899080-95e0-11e9-9614-bb683703a164.png) |
| Text baselines aligned | Text baselines aligned | Text baselines **not aligned** |
| Oval day selector (25x27px) | Oval day selector (31x32px) | Round day selector (37x37px) |

Results improve if the `margin` properties in both `.calendar-day-base` and `.calendar-week-number` are also set to use `em` (and the `padding` in `.calendar-week-number` adjusted):

```scss
.calendar-day-base {
  ...
  width: 2.4em; height: 2.4em;
  padding: 0.1em;
  margin: 0.2em;
  border-radius: 1.4em;
  ...
```
```scss
.calendar-week-number {
  ...
  width: 2.3em; height: 1.8em;
  border-radius: 2px;
  padding: 0.6em 0 0;
  margin: 0.5em 6px;
  ...
}
```

| Scaling factor = 1.0 | Scaling factor = 1.25 | Scaling factor = 1.5 |
| :--- | :--- | :--- |
| ![calendar-arc-1-fixed](https://user-images.githubusercontent.com/18715287/59979121-b5b28080-95e3-11e9-9857-634d1dceb1b2.png) | ![calendar-arc-1 25-fixed](https://user-images.githubusercontent.com/18715287/59979130-df6ba780-95e3-11e9-86e1-8a7ede5b1ba7.png) | ![calendar-arc-1 5-fixed](https://user-images.githubusercontent.com/18715287/59979145-0f1aaf80-95e4-11e9-8513-88f98583dfe2.png) |
| Text baselines aligned | Text baselines aligned | Text baselines aligned |
| Round day selector (25x25px) | Round day selector (31x31px) | Round day selector (37x37px) |

Still not a foolproof solution though imo. This does seem to be a buggy implementation upstream, as `.calendar-week-number` for some reason does not center text vertically - if it did,  it would be relatively easy to match the vertical space (height + margins) occupied by `.calendar-week-number` and `.calendar-day-base` to ensure consistent line spacing. As it is, the `padding` used in `.calendar-week-number` to align the text appears to be messing things up (for certain values of text scaling).

**Comment by jnsh** [comment]
Upstream is using only `px` values for the margins, so I'd rather not change them. Especially on such a complex area of the code it could lead to more issues, and it's best to try to follow the upstream stylesheet if possible.

I need to focus on some other work atm, but I can take a closer look at this later, if you've run out of ideas.

**Comment by drakkar1969** [comment]
Fair enough. I am out if ideas for the moment, will leave the issue open

**Comment by jnsh** [comment]
This should be fixed with https://github.com/jnsh/arc-theme/commit/5922658f7b7358aa597d1dab5ce7027ea5dff850.

Oddly enough, I couldn't reproduce your results after only changing the `width`, `height` and `border-radius` to use `em` in `.calendar-day-base` (although I used different values). For me the date selector remains perfectly round regardless of the text scaling factor. Let me know if this is not the case for you.

The vertical alignment of `.calendar-week-number` is still off after the fix when text scaling is used, but this seems to be the case also for the default shell theme. It seems that the top padding for the week number is not being scaled with the text for some reason, even though it's using `em`. However, that seems out of the scope of this issue, and I'll investigate it further at some point.

Thanks again for the report.

**Comment by drakkar1969** [comment]
Thanks, this fixes the date selector shape for me. Nice fix for the weather forecast labels too - which was another issue that was bugging me.
