### ISSUE TITLE
[Feature Request] Using light(inverse) border color in dark variant

### ISSUE THREAD

**Issue by ceyhunn** [jnsh/arc-theme#43]
- Distribution and version: Manjaro Linux 20,  AUR latest
- Versions for the affected applications/desktops/tookits:

**Comment by jnsh** [comment]
Thank you for the suggestion.

The existing theme style/design won't ever be changed. Therefore, to implement your request we'd have to either add a new variant, or a build option that implements this. However adding either of the aforementioned for small design changes such as this is very time consuming, and would result in endless variant/build option additions for every small style change someone might want.

The "right" way to do this, is in a separate fork. Since this kind of change should mostly require color variable and asset changes, the fork should be fairly simple to keep in sync with upstream as well.

**Comment by ceyhunn** [comment]
Dark variant with light border color looks cool in every theme. Ok, no problem.
