### ISSUE TITLE
Base repository

### ISSUE THREAD

**Issue by actionless** [jnsh/arc-theme#47]
This repo forked from outdated https://github.com/horst3180/arc-theme instead of https://github.com/arc-design/arc-theme

Due to that all infrastructure for changing the color of the theme (like this script and its deps https://github.com/arc-design/arc-theme/blob/master/change_color.sh, https://github.com/arc-design/arc-theme/blob/863d0a14ce518e0c3f0c28881d33cbd7d2adad5e/common/gtk-3.0/_colors.scss.thpl, etc) are not presented in this fork

**Comment by jnsh** [comment]
> This repo forked from outdated https://github.com/horst3180/arc-theme instead of https://github.com/arc-design/arc-theme

Yes, this was intentional choice. The `arc-design/arc-theme` repo had included a number of problematic changes, and instead of cleaning those, I found it easier to use the original repo as a starting point.

I decided not to cherry-pick the oomox support for at least the following reasons:
- If there's an officially supported way for changing the colors for the theme, it should work on *every* component of the theme, and not only for the GTK themes.
- There was zero documentation for the color changing scripts. Not even a mention that they are meant to be used with a third party tool.
- If the them included a support for changing the colors, it should be part of the build system, and not a third party script that can't be guaranteed to work.
- At the time I looked at this, I saw reports that changing the colors for some parts of the GTK themes weren't working, although this may have since been fixed.

That's just off the top of my head, and there may have been other problems as well.

I'm not against supporting oomox on this repo, but I'm not in favor for including bunch of complicated scripts all over the source code, that have nothing to do with the actual project. Also, I'd imagine al the scripts could be included, and made to work from inside the oomox code base as well.

If there's something else that could be done to help with the oomox/themix support, let me know and I can look into it.

**Comment by actionless** [comment]
yup, if you can implement defining main colors as part of base system, oomox plugin could call that build system instead of change_color script, that doesn't matter at all

**Comment by jnsh** [comment]
Just to clarify, I have no plans on adding any kind of color changing options to the build system. I did look into it earlier, but abandoned the idea as implementing it for every part of the theme would get far too complex, and I couldn't think of a good way for configuring every individual color with the current build system.

What I meant above, that *if* there was officially supported way for changing the colors, it should be part of the build system instead of set of separate scripts.

If you want to keep supporting Arc theme from this repo with oomox, I'd suggest including the color changing scripts in the oomox code, and e.g. copying the over during the theme rebuild, if that could work.

**Comment by actionless** [comment]
i personally use only Numix and Materia-based themes on my setups, so unless somebody gonna do that, the support for Arc will be dropped in the next GTK theme API change.

**Comment by jnsh** [comment]
If there's no-one actually maintaining the Arc support for oomox, that's another good reason for including any kind of support for it in the actual theme.

Closing, as I think this isn't really an issue on this project. Feel free to continue the discussion regardless, if there's anything to add.
