### ISSUE TITLE
IceWM support

### ISSUE THREAD

**Issue by Brottweiler** [jnsh/arc-theme#49]
There's an abandoned Arc Dark theme for IceWM over at https://github.com/Aethusx/icewm-arc-dark

Would it be possible to integrate it into this repo, similar to how the Openbox theme was integrated? 

There are some bugs with the IceWM theme because I assume it's outdated.

**Comment by jnsh** [comment]
I have no intentions for adding any additional themes to this project, especially if they come from existing project that anyone could already use if they wanted, and have known issues. Another problem is that IceWM theme is unlicensed.

If the theme is still being maintained, I could e.g. mention it on the README.

**Comment by jnsh** [comment]
A bit more explanation since my earlier reply was quite blunt.

The main problem is that every additional theme creates more maintenance work, in addition to the work required for actual inclusion of the theme. It's not feasible to include support for every possible WM someone might wish, so the supported themes are limited to GTK based desktop environments.

I originally added the openbox theme from the [`arc-design/arc-theme`](https://github.com/arc-design/arc-theme) repo, under the impression that it was specifically created for that project. Only later I learned that it was simply copied from a separate project, and I've been considering removing the openbox theme for that reason for some time.

Thank you for your suggestion regardless, and for bringing the IceWM theme to my attention. If the theme is actively maintained, and got more complete it would definitely make sense to at least mention it somewhere within this project.

**Comment by Brottweiler** [comment]
Thanks for your reply! I totally understand your reasoning.

**Comment by Brottweiler** [comment]
@jnsh Hello again! I just wanted to let you know that I have forked the Arc Dark theme for IceWM in an attempt to fix the issues with it and keep it up to date. 

Just in case you felt like _mentioning_ it somewhere, here's the link https://github.com/Brottweiler/icewm-arc-dark.

If not, I understand!
