### ISSUE TITLE
Lighter color behind system monitor bars not visible in Arc-Dark

### ISSUE THREAD

**Issue by philipzae** [jnsh/arc-theme#58]
- Distribution and version: Xubuntu 20.04
- Versions for the affected applications/desktops/tookits: xfce4-genmon-plugin 4.0.2-1

I'm using Arc-Dark, but the color difference between the panel color and the bar background color is to small to be noticed.
![image](https://user-images.githubusercontent.com/4412114/86114841-2ab07400-badc-11ea-8ff4-3160c066655f.png)

With Arc and Arc-Darker, the bar background color is white, so its easy to see it from the panel background color.
![image](https://user-images.githubusercontent.com/4412114/86115049-7105d300-badc-11ea-86aa-c686053644f8.png)

**Comment by jnsh** [comment]
I think the only way to style the genmod `<bar>` consistently with rest of the panel widgets, is to use slightly darker background for all theme variants (lighter variant on the right, all other variants would look like on the left):
![Screenshot_genmon](https://user-images.githubusercontent.com/39574454/86352732-ec978980-bc6e-11ea-8d22-c147fef4f95b.png)

Let me know if you have any feedback for this, or anything else that could be fixed/improved for the genmod plugin while I'm at it. Otherwise I'll push the above fix in the near future.

**Comment by philipzae** [comment]
That seems fine
