### ISSUE TITLE
Transparent background in the GNOME Terminal scrollbar 

### ISSUE THREAD

**Issue by sagcan** [jnsh/arc-theme#74]
More a feature request rather than an issue. I was wondering if it'd be possible to implement this nice little "feature" as I personally don't think a background for the scrollbar is needed inside the GNOME Terminal and furthermore gives a nice minimalist look to it. Any thoughts to it?
![before](https://user-images.githubusercontent.com/29666622/92277303-ecc43780-eef2-11ea-8de2-4c6d530171c7.png)
![after](https://user-images.githubusercontent.com/29666622/92277299-ec2ba100-eef2-11ea-84a3-0107cccf9662.png)

**Comment by jnsh** [comment]
Looks like transparent background wouldn't work as you hoped in gnome-terminal, as the scrollbar is drawn next to the vte-terminal area, rather than above it. Even if that wasn't the case, there are a few reasons why I'd prefer to not implement this.

However, you can change the scrollbar background color for your user to match the terminal background, by injecting something like the following CSS rule in `~/.config/gtk-3.0/gtk.css` (replace `red` with [working CSS color value/name](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) of your terminal background color):
```
terminal-screen-container scrollbar {
  background: red;
}
```

Hope this helps. Closing this issue as WONTFIX.
