### ISSUE TITLE
Search button weird on nautilus gnome 3.38

### ISSUE THREAD

**Issue by daniel88ferreira** [jnsh/arc-theme#85]
Hello,

Just updated to gnome 3.38 and search button on files (nautilus) moved more or less to the middle. With arc theme it looks weird:
![Screenshot from 2020-10-06 22-42-16](https://user-images.githubusercontent.com/23555804/95263869-5d2de380-0826-11eb-9fb7-e14a610d87a7.png)

I am not a fan of the Adwaita solution, but it looks better:
![image](https://user-images.githubusercontent.com/23555804/95264037-a0885200-0826-11eb-9669-4bd0f287f658.png)

Thanks! And thanks for the great work!

**Comment by jnsh** [comment]
Thanks for the report. I had already looked at this, but unfortunately there's no simple fix.

The search button placement itself has nothing to do with the theme. Nautilus [added](https://gitlab.gnome.org/GNOME/nautilus/-/merge_requests/475#note_735820) some spacing between it and rest of the header buttons, as part of the path-bar refactoring. I'm not a big fan of this either, although I understand the reasoning. There is an [open nautilus issue](https://gitlab.gnome.org/GNOME/nautilus/-/issues/1627) about this.

The solution would be adding some background and borders for the overall path-bar area, similarly that was done for the "maximized" path-bar in earlier versions, and how the Adwaita specific nautilus styling was done, as seen in the screenshot you provided.

The problem is that it's not possible to style nautilus 3.36 and 3.38 separately in custom GTK themes, and implementing the above fix would alter/break the path-bar styling for pre-3.38 versions.

For that reason the fix requires some further testing and consideration, but I'm hoping to get some kind of solution pushed soon.
